version: '2'
mpp-vars:
  name: local_container
  use_containers_extra_store: true

pipelines:
- name: rootfs
  build: name:build
  stages:

  # Install some special RPMs
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: distro_gpg_keys
      disable_dracut: true
      exclude:
        docs: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          ignore-weak-deps: true
          module-platform-id: $distro_module_id
          baseurl: $distro_baseurl_repo
          repos:
            mpp-join:
            - mpp-eval: image_repos
            - mpp-eval: extra_repos
          packages:
            mpp-join:
            - mpp-eval: image_rpms
            - - hostname
              - openssh-clients
              - openssh-server
              - podman
              - vim
              - wget
          excludes:
          - dracut-config-rescue

  # Get the auto-apps container image from the local storage
  - type: org.osbuild.skopeo
    inputs:
      images:
        type: org.osbuild.containers
        origin: org.osbuild.source
        mpp-resolve-images:
          images:
            - source: "localhost/auto-apps"
              tag: latest
              name: "localhost/auto-apps"
              containers-transport: containers-storage
    options:
      destination:
        type: containers-storage
        storage-path:
          mpp-eval: containers_extra_store

  - type: org.osbuild.containers.unit.create
    options:
      filename: radio.container
      config:
        Unit:
          Description: Demo radio service container
          Requires:
            - routingmanagerd.socket
          Wants:
            - engine.service
        Container:
          Image: localhost/auto-apps
          Exec: /usr/bin/radio-service
          Volume:
            - /run/vsomeip:/run/vsomeip
        Service:
          Restart: always
        Install:
          WantedBy:
            - multi-user.target

  - type: org.osbuild.containers.unit.create
    options:
      filename: engine.container
      config:
        Unit:
          Description: Demo engine service container
          Requires:
            - routingmanagerd.socket
        Container:
          Image: localhost/auto-apps
          Exec: /usr/bin/engine-service
          Volume:
            - /run/vsomeip:/run/vsomeip
        Service:
          Restart: always
        Install:
          WantedBy:
            - multi-user.target
